
name: 42-project-badge-d01
on:
  push:
    branches: [ "main" ]
    paths:
        - d01/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: 42 Project Badge
        uses: Korkrane/42project-badge-action@v1.0.2
        with:
          login: bahaas
          project: 'Python Module 01'
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 990a037d04c9a3b71a62aa5df94cac00
